/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_litecam_LiteCam */

#ifndef _Included_com_example_litecam_LiteCam
#define _Included_com_example_litecam_LiteCam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_litecam_LiteCam
 * Method:    listDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_litecam_LiteCam_listDevices
  (JNIEnv *, jclass);

/*
 * Class:     com_example_litecam_LiteCam
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_litecam_LiteCam_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_litecam_LiteCam
 * Method:    nativeClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_litecam_LiteCam_nativeClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_litecam_LiteCam
 * Method:    listSupportedResolutions
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_litecam_LiteCam_listSupportedResolutions
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_litecam_LiteCam
 * Method:    setResolution
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_litecam_LiteCam_setResolution
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_example_litecam_LiteCam
 * Method:    captureFrame
 * Signature: (ILjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_litecam_LiteCam_captureFrame
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_example_litecam_LiteCam
 * Method:    getFrameWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_litecam_LiteCam_getFrameWidth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_litecam_LiteCam
 * Method:    getFrameHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_litecam_LiteCam_getFrameHeight
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
